function f = create_shape_function(num_node_per_element, schemes)
%
% shape function and derivatives.
%
% @since 1.1.0
% @param {number} [num_node_per_element] 一個 element 有幾個 nodes.
% @param {string} [schemes] corner first or along boundary.
% @return {function} [shape_function] for Q4 Q8 Q9.
%
% @param {sym} [eta] 一個 element 有幾個 nodes.
% @param {sym} [xi] natural coordinates (-1 ... +1).
% @param {array} [shape] Shape functions.
% @return {array} [diff_shape] derivatives w.r.t. xi and eta.
%

    switch num_node_per_element

        case 4
            f = @shape_function_Q4;

        case 6
            f = @shapeFunctionT6;

        case 8
            if nargin == 1 || strcmp(schemes, 'corner_first')
                f = @shape_function_Q8;
            else
                f = @shape_function_Q8_along_boundary;
            end

        case 9
            if nargin == 1 || strcmp(schemes, 'corner_first')
                f = @shape_function_Q9;
            else
                f = @shape_function_Q9_along_boundary;
            end

    end

    function [shape, diff_shape] = shapeFunctionT6(xi2, xi3)

    % shape function and derivatives for T6 elements
    % shape : Shape functions
    % naturalDerivatives: derivatives w.r.t. xi and eta
    % xi, eta: natural coordinates (-1 ... +1)
        xi1 = 1 - xi2 -xi3;

        shape = [ xi1*(2*xi1-1), xi2*(2*xi2-1), xi3*(2*xi3-1), 4*xi1*xi2, 4*xi2*xi3, 4*xi3*xi1];

        diff_shape = [
            4*xi2 + 4*xi3 - 3, 4*xi2 - 1,         0, 4 - 4*xi3 - 8*xi2, 4*xi3,            -4*xi3;
            4*xi2 + 4*xi3 - 3,         0, 4*xi3 - 1,            -4*xi2, 4*xi2, 4 - 8*xi3 - 4*xi2;
        ];

    end % end function shapeFunctionQ4

    function [shape, diff_shape] = shape_function_Q4(xi, eta)

        shape = 1 / 4 * [ (1 - xi) * (1 - eta), (1 + xi) * (1 - eta), (1 + xi) * (1 + eta), (1 - xi) * (1 + eta)];

        diff_shape = 1 / 4 * [
            - (1 - eta), 1 - eta, 1 + eta, - (1 + eta);
            - (1 - xi), - (1 + xi), 1 + xi, 1 - xi;
        ];

    end

    function [shape, diff_shape] = shape_function_Q8(xi, eta)

        shape = 1 / 4 * [
            (1-xi)*(1-eta)*(-xi-eta-1), ...
            (1+xi)*(1-eta)*(xi-eta-1), ...
            (1+xi)*(1+eta)*(xi+eta-1), ...
            (1-xi)*(1+eta)*(-xi+eta-1), ...
            2*(1-eta)*(1-xi^2), ...
            2*(1+xi)*(1-eta^2), ...
            2*(1+eta)*(1-xi^2), ...
            2*(1-xi)*(1-eta^2)
        ];

        diff_shape = [
            - ((eta - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            ((eta - 1)*(eta - xi + 1))/4 - ((eta - 1)*(xi + 1))/4, ...
            ((eta + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            ((eta + 1)*(xi - eta + 1))/4 + ((eta + 1)*(xi - 1))/4, ....
            (xi*(2*eta - 2))/2, ...
            1/2 - eta^2/2, ...
            -(xi*(2*eta + 2))/2, ...
            eta^2/2 - 1/2;

            - ((xi - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            ((xi + 1)*(eta - xi + 1))/4 + ((eta - 1)*(xi + 1))/4, ...
            ((xi + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            ((xi - 1)*(xi - eta + 1))/4 - ((eta + 1)*(xi - 1))/4, ...
            xi^2/2 - 1/2, ....
            -(eta*(2*xi + 2))/2, ...
            1/2 - xi^2/2, ...
            (eta*(2*xi - 2))/2
        ];

    end

    function [shape, diff_shape] = shape_function_Q9(xi, eta)

        shape = [
            (eta*xi*(eta - 1)*(xi - 1))/4, ...
            (eta*xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            (eta*xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            (eta*xi*(eta + 1)*(xi - 1))/4, ...
            -(eta*(eta - 1)*(xi - 1)*(xi + 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1)*(eta + 1), ...
            -(eta*(eta + 1)*(xi - 1)*(xi + 1))/2, ...
            -(xi*(eta - 1)*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(eta + 1)*(xi - 1)*(xi + 1)
        ];

        diff_shape = [
            (eta*xi*(eta - 1))/4 + (eta*(eta - 1)*(xi - 1))/4,...
            (eta*xi*(eta - 1))/4 + (eta*(xi/2 + 1/2)*(eta - 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(xi/2 + 1/2)*(eta + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(eta + 1)*(xi - 1))/4,...
            -(eta*(eta - 1)*(xi - 1))/2 - (eta*(eta - 1)*(xi + 1))/2,...
            -(xi/2 + 1/2)*(eta - 1)*(eta + 1) - (xi*(eta - 1)*(eta + 1))/2,...
            -(eta*(eta + 1)*(xi - 1))/2 - (eta*(eta + 1)*(xi + 1))/2,...
            -(xi*(eta - 1)*(eta + 1))/2 - ((eta - 1)*(eta + 1)*(xi - 1))/2,...
            (eta - 1)*(eta + 1)*(xi - 1) + (eta - 1)*(eta + 1)*(xi + 1);

            (eta*xi*(xi - 1))/4 + (xi*(eta - 1)*(xi - 1))/4, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            (eta*xi*(xi - 1))/4 + (xi*(eta + 1)*(xi - 1))/4, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta - 1)*(xi - 1)*(xi + 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1) - xi*(xi/2 + 1/2)*(eta + 1), ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta + 1)*(xi - 1)*(xi + 1))/2, ...
            -(xi*(eta - 1)*(xi - 1))/2 - (xi*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(xi - 1)*(xi + 1) + (eta + 1)*(xi - 1)*(xi + 1)
        ];

    end

    function [shape, diff_shape] = shape_function_Q8_along_boundary(xi, eta)

        shape = 1 / 4 * [
            (1-xi)*(1-eta)*(-xi-eta-1), ...
            2*(1-eta)*(1-xi^2), ...
            (1+xi)*(1-eta)*(xi-eta-1), ...
            2*(1+xi)*(1-eta^2), ...
            (1+xi)*(1+eta)*(xi+eta-1), ...
            2*(1+eta)*(1-xi^2), ...
            (1-xi)*(1+eta)*(-xi+eta-1), ...
            2*(1-xi)*(1-eta^2)
        ];

        diff_shape = [
            - ((eta - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            (xi*(2*eta - 2))/2, ...
            ((eta - 1)*(eta - xi + 1))/4 - ((eta - 1)*(xi + 1))/4, ...
            1/2 - eta^2/2, ...
            ((eta + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            -(xi*(2*eta + 2))/2, ...
            ((eta + 1)*(xi - eta + 1))/4 + ((eta + 1)*(xi - 1))/4, ....
            eta^2/2 - 1/2;

            - ((xi - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            xi^2/2 - 1/2, ....
            ((xi + 1)*(eta - xi + 1))/4 + ((eta - 1)*(xi + 1))/4, ...
            -(eta*(2*xi + 2))/2, ...
            ((xi + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            1/2 - xi^2/2, ...
            ((xi - 1)*(xi - eta + 1))/4 - ((eta + 1)*(xi - 1))/4, ...
            (eta*(2*xi - 2))/2
        ];

    end

    function [shape, diff_shape] = shape_function_Q9_along_boundary(xi, eta)

        shape = [
            (eta*xi*(eta - 1)*(xi - 1))/4, ...
            -(eta*(eta - 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1)*(eta + 1), ...
            (eta*xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            -(eta*(eta + 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(eta + 1)*(xi - 1))/4, ...
            -(xi*(eta - 1)*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(eta + 1)*(xi - 1)*(xi + 1)
        ];

        diff_shape = [
            (eta*xi*(eta - 1))/4 + (eta*(eta - 1)*(xi - 1))/4,...
            -(eta*(eta - 1)*(xi - 1))/2 - (eta*(eta - 1)*(xi + 1))/2,...
            (eta*xi*(eta - 1))/4 + (eta*(xi/2 + 1/2)*(eta - 1))/2,...
            -(xi/2 + 1/2)*(eta - 1)*(eta + 1) - (xi*(eta - 1)*(eta + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(xi/2 + 1/2)*(eta + 1))/2,...
            -(eta*(eta + 1)*(xi - 1))/2 - (eta*(eta + 1)*(xi + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(eta + 1)*(xi - 1))/4,...
            -(xi*(eta - 1)*(eta + 1))/2 - ((eta - 1)*(eta + 1)*(xi - 1))/2,...
            (eta - 1)*(eta + 1)*(xi - 1) + (eta - 1)*(eta + 1)*(xi + 1);

            (eta*xi*(xi - 1))/4 + (xi*(eta - 1)*(xi - 1))/4, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta - 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1) - xi*(xi/2 + 1/2)*(eta + 1), ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta + 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi - 1))/4 + (xi*(eta + 1)*(xi - 1))/4, ...
            -(xi*(eta - 1)*(xi - 1))/2 - (xi*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(xi - 1)*(xi + 1) + (eta + 1)*(xi - 1)*(xi + 1)
        ];

    end

end
