function f = createShapeFunction(numNodePerElement, schemes)
%
% shape function and derivatives.
%
% @since 2.1.0
% @param {number} [numNodePerElement] 一個 element 有幾個 nodes.
% @param {string} [schemes] corner first or along boundary.
% @return {function} [shapeFunction] for Q4 Q8 Q9.
%
% @param {sym} [eta] 一個 element 有幾個 nodes.
% @param {sym} [xi] natural coordinates (-1 ... +1).
% @param {array} [shape] Shape functions.
% @return {array} [naturalDerivatives] derivatives w.r.t. xi and eta.
%

    switch numNodePerElement

        case 4
            f = @shapeFunctionQ4;

        case 8
            if nargin == 1 || strcmp(schemes, 'cornerFirst')
                f = @shapeFunctionQ8;
            else
                f = @shapeFunctionQ8AlongBoundary;
            end

        case 9
            if nargin == 1 || strcmp(schemes, 'cornerFirst')
                f = @shapeFunctionQ9;
            else
                f = @shapeFunctionQ9AlongBoundary;
            end

    end

    function [shape, naturalDerivatives] = shapeFunctionQ4(xi, eta)

        shape = 1 / 4 * [ (1 - xi) * (1 - eta), (1 + xi) * (1 - eta), (1 + xi) * (1 + eta), (1 - xi) * (1 + eta)];

        naturalDerivatives = 1 / 4 * [
            - (1 - eta), 1 - eta, 1 + eta, - (1 + eta);
            - (1 - xi), - (1 + xi), 1 + xi, 1 - xi;
        ];

    end

    function [shape, naturalDerivatives] = shapeFunctionQ8(xi, eta)

        shape = 1 / 4 * [
            (1-xi)*(1-eta)*(-xi-eta-1), ...
            (1+xi)*(1-eta)*(xi-eta-1), ...
            (1+xi)*(1+eta)*(xi+eta-1), ...
            (1-xi)*(1+eta)*(-xi+eta-1), ...
            2*(1-eta)*(1-xi^2), ...
            2*(1+xi)*(1-eta^2), ...
            2*(1+eta)*(1-xi^2), ...
            2*(1-xi)*(1-eta^2)
        ];

        naturalDerivatives = [
            - ((eta - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            ((eta - 1)*(eta - xi + 1))/4 - ((eta - 1)*(xi + 1))/4, ...
            ((eta + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            ((eta + 1)*(xi - eta + 1))/4 + ((eta + 1)*(xi - 1))/4, ....
            (xi*(2*eta - 2))/2, ...
            1/2 - eta^2/2, ...
            -(xi*(2*eta + 2))/2, ...
            eta^2/2 - 1/2;

            - ((xi - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            ((xi + 1)*(eta - xi + 1))/4 + ((eta - 1)*(xi + 1))/4, ...
            ((xi + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            ((xi - 1)*(xi - eta + 1))/4 - ((eta + 1)*(xi - 1))/4, ...
            xi^2/2 - 1/2, ....
            -(eta*(2*xi + 2))/2, ...
            1/2 - xi^2/2, ...
            (eta*(2*xi - 2))/2
        ];

    end

    function [shape, naturalDerivatives] = shapeFunctionQ9(xi, eta)

        shape = [
            (eta*xi*(eta - 1)*(xi - 1))/4, ...
            (eta*xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            (eta*xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            (eta*xi*(eta + 1)*(xi - 1))/4, ...
            -(eta*(eta - 1)*(xi - 1)*(xi + 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1)*(eta + 1), ...
            -(eta*(eta + 1)*(xi - 1)*(xi + 1))/2, ...
            -(xi*(eta - 1)*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(eta + 1)*(xi - 1)*(xi + 1)
        ];

        naturalDerivatives = [
            (eta*xi*(eta - 1))/4 + (eta*(eta - 1)*(xi - 1))/4,...
            (eta*xi*(eta - 1))/4 + (eta*(xi/2 + 1/2)*(eta - 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(xi/2 + 1/2)*(eta + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(eta + 1)*(xi - 1))/4,...
            -(eta*(eta - 1)*(xi - 1))/2 - (eta*(eta - 1)*(xi + 1))/2,...
            -(xi/2 + 1/2)*(eta - 1)*(eta + 1) - (xi*(eta - 1)*(eta + 1))/2,...
            -(eta*(eta + 1)*(xi - 1))/2 - (eta*(eta + 1)*(xi + 1))/2,...
            -(xi*(eta - 1)*(eta + 1))/2 - ((eta - 1)*(eta + 1)*(xi - 1))/2,...
            (eta - 1)*(eta + 1)*(xi - 1) + (eta - 1)*(eta + 1)*(xi + 1);

            (eta*xi*(xi - 1))/4 + (xi*(eta - 1)*(xi - 1))/4, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            (eta*xi*(xi - 1))/4 + (xi*(eta + 1)*(xi - 1))/4, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta - 1)*(xi - 1)*(xi + 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1) - xi*(xi/2 + 1/2)*(eta + 1), ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta + 1)*(xi - 1)*(xi + 1))/2, ...
            -(xi*(eta - 1)*(xi - 1))/2 - (xi*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(xi - 1)*(xi + 1) + (eta + 1)*(xi - 1)*(xi + 1)
        ];

    end

    function [shape, naturalDerivatives] = shapeFunctionQ8AlongBoundary(xi, eta)

        shape = 1 / 4 * [
            (1-xi)*(1-eta)*(-xi-eta-1), ...
            2*(1-eta)*(1-xi^2), ...
            (1+xi)*(1-eta)*(xi-eta-1), ...
            2*(1+xi)*(1-eta^2), ...
            (1+xi)*(1+eta)*(xi+eta-1), ...
            2*(1+eta)*(1-xi^2), ...
            (1-xi)*(1+eta)*(-xi+eta-1), ...
            2*(1-xi)*(1-eta^2)
        ];

        naturalDerivatives = [
            - ((eta - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            (xi*(2*eta - 2))/2, ...
            ((eta - 1)*(eta - xi + 1))/4 - ((eta - 1)*(xi + 1))/4, ...
            1/2 - eta^2/2, ...
            ((eta + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            -(xi*(2*eta + 2))/2, ...
            ((eta + 1)*(xi - eta + 1))/4 + ((eta + 1)*(xi - 1))/4, ....
            eta^2/2 - 1/2;

            - ((xi - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            xi^2/2 - 1/2, ....
            ((xi + 1)*(eta - xi + 1))/4 + ((eta - 1)*(xi + 1))/4, ...
            -(eta*(2*xi + 2))/2, ...
            ((xi + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            1/2 - xi^2/2, ...
            ((xi - 1)*(xi - eta + 1))/4 - ((eta + 1)*(xi - 1))/4, ...
            (eta*(2*xi - 2))/2
        ];

    end

    function [shape, naturalDerivatives] = shapeFunctionQ9AlongBoundary(xi, eta)

        shape = [
            (eta*xi*(eta - 1)*(xi - 1))/4, ...
            -(eta*(eta - 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1)*(eta + 1), ...
            (eta*xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            -(eta*(eta + 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(eta + 1)*(xi - 1))/4, ...
            -(xi*(eta - 1)*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(eta + 1)*(xi - 1)*(xi + 1)
        ];

        naturalDerivatives = [
            (eta*xi*(eta - 1))/4 + (eta*(eta - 1)*(xi - 1))/4,...
            -(eta*(eta - 1)*(xi - 1))/2 - (eta*(eta - 1)*(xi + 1))/2,...
            (eta*xi*(eta - 1))/4 + (eta*(xi/2 + 1/2)*(eta - 1))/2,...
            -(xi/2 + 1/2)*(eta - 1)*(eta + 1) - (xi*(eta - 1)*(eta + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(xi/2 + 1/2)*(eta + 1))/2,...
            -(eta*(eta + 1)*(xi - 1))/2 - (eta*(eta + 1)*(xi + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(eta + 1)*(xi - 1))/4,...
            -(xi*(eta - 1)*(eta + 1))/2 - ((eta - 1)*(eta + 1)*(xi - 1))/2,...
            (eta - 1)*(eta + 1)*(xi - 1) + (eta - 1)*(eta + 1)*(xi + 1);

            (eta*xi*(xi - 1))/4 + (xi*(eta - 1)*(xi - 1))/4, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta - 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1) - xi*(xi/2 + 1/2)*(eta + 1), ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta + 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi - 1))/4 + (xi*(eta + 1)*(xi - 1))/4, ...
            -(xi*(eta - 1)*(xi - 1))/2 - (xi*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(xi - 1)*(xi + 1) + (eta + 1)*(xi - 1)*(xi + 1)
        ];

    end

end
