function [shape, diff_shape] = shape_function_Q9(xi, eta)
%
% shape function and derivatives for Q9 elements.
%
% @since 1.0.0
% @param {sym} [xi] natural coordinates (-1 ... +1).
% @param {sym} [eta] natural coordinates (-1 ... +1).
% @param {array} [shape] Shape functions.
% @return {array} [diff_shape] derivatives w.r.t. xi and eta.

    shape = [
        (eta*xi*(eta - 1)*(xi - 1))/4, ...
        (eta*xi*(xi/2 + 1/2)*(eta - 1))/2, ...
        (eta*xi*(xi/2 + 1/2)*(eta + 1))/2, ...
        (eta*xi*(eta + 1)*(xi - 1))/4, ...
        -(eta*(eta - 1)*(xi - 1)*(xi + 1))/2, ...
        -xi*(xi/2 + 1/2)*(eta - 1)*(eta + 1), ...
        -(eta*(eta + 1)*(xi - 1)*(xi + 1))/2, ...
        -(xi*(eta - 1)*(eta + 1)*(xi - 1))/2, ...
        (eta - 1)*(eta + 1)*(xi - 1)*(xi + 1)
    ];

    diff_shape = [
        (eta*xi*(eta - 1))/4 + (eta*(eta - 1)*(xi - 1))/4,...
        (eta*xi*(eta - 1))/4 + (eta*(xi/2 + 1/2)*(eta - 1))/2,...
        (eta*xi*(eta + 1))/4 + (eta*(xi/2 + 1/2)*(eta + 1))/2,...
        (eta*xi*(eta + 1))/4 + (eta*(eta + 1)*(xi - 1))/4,...
        -(eta*(eta - 1)*(xi - 1))/2 - (eta*(eta - 1)*(xi + 1))/2,...
        -(xi/2 + 1/2)*(eta - 1)*(eta + 1) - (xi*(eta - 1)*(eta + 1))/2,...
        -(eta*(eta + 1)*(xi - 1))/2 - (eta*(eta + 1)*(xi + 1))/2,...
        -(xi*(eta - 1)*(eta + 1))/2 - ((eta - 1)*(eta + 1)*(xi - 1))/2,...
        (eta - 1)*(eta + 1)*(xi - 1) + (eta - 1)*(eta + 1)*(xi + 1);
        (eta*xi*(xi - 1))/4 + (xi*(eta - 1)*(xi - 1))/4, ...
        (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta - 1))/2, ...
        (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta + 1))/2, ...
        (eta*xi*(xi - 1))/4 + (xi*(eta + 1)*(xi - 1))/4, ...
        -(eta*(xi - 1)*(xi + 1))/2 - ((eta - 1)*(xi - 1)*(xi + 1))/2, ...
        -xi*(xi/2 + 1/2)*(eta - 1) - xi*(xi/2 + 1/2)*(eta + 1), ...
        -(eta*(xi - 1)*(xi + 1))/2 - ((eta + 1)*(xi - 1)*(xi + 1))/2, ...
        -(xi*(eta - 1)*(xi - 1))/2 - (xi*(eta + 1)*(xi - 1))/2, ...
        (eta - 1)*(xi - 1)*(xi + 1) + (eta + 1)*(xi - 1)*(xi + 1)
    ];

end

