function f = createShapeFunction(numNodePerElement, schemes)
%
% shape function and derivatives.
%
% @since 2.1.0
% @param {number} [numNodePerElement] 一個 element 有幾個 nodes.
% @param {string} [schemes] corner first or along boundary.
% @return {function} [shapeFunction] for Q4 Q8 Q9.
%
% @param {sym} [eta] 一個 element 有幾個 nodes.
% @param {sym} [xi] natural coordinates (-1 ... +1).
% @param {array} [shape] Shape functions.
% @return {array} [naturalDerivatives] derivatives w.r.t. xi and eta.
%

    switch numNodePerElement

        case 4
            f = @shapeFunctionQ4;

        case 8
            if nargin == 1 || strcmp(schemes, 'cornerFirst')
                f = @shapeFunctionQ8;
            else
                f = @shapeFunctionQ8AlongBoundary;
            end

        case 9
            if nargin == 1 || strcmp(schemes, 'cornerFirst')
                f = @shapeFunctionQ9;
            else
                f = @shapeFunctionQ9AlongBoundary;
            end

        case 16
            syms xi eta; % be careful performance issue.

            nodes = linspace(-1, 1, 4);
            nodes_length = length(nodes);

            shape_xi_1 = lagrange_interpolation(nodes, 1, xi);
            shape_xi_2 = lagrange_interpolation(nodes, 2, xi);
            shape_xi_3 = lagrange_interpolation(nodes, 3, xi);
            shape_xi_4 = lagrange_interpolation(nodes, 4, xi);
            shape_eta_1 = lagrange_interpolation(nodes, 1, eta);
            shape_eta_2 = lagrange_interpolation(nodes, 2, eta);
            shape_eta_3 = lagrange_interpolation(nodes, 3, eta);
            shape_eta_4 = lagrange_interpolation(nodes, 4, eta);

            shape = sym(zeros(1, nodes_length));
            shape(1) = shape_xi_1 * shape_eta_1;
            shape(2) = shape_xi_4 * shape_eta_1;
            shape(3) = shape_xi_4 * shape_eta_4;
            shape(4) = shape_xi_1 * shape_eta_4;
            shape(5) = shape_xi_2 * shape_eta_1;
            shape(6) = shape_xi_3 * shape_eta_1;
            shape(7) = shape_xi_4 * shape_eta_2;
            shape(8) = shape_xi_4 * shape_eta_3;
            shape(9) = shape_xi_3 * shape_eta_4;
            shape(10) = shape_xi_2 * shape_eta_4;
            shape(11) = shape_xi_1 * shape_eta_3;
            shape(12) = shape_xi_1 * shape_eta_2;
            shape(13) = shape_xi_2 * shape_eta_2;
            shape(14) = shape_xi_3 * shape_eta_2;
            shape(15) = shape_xi_3 * shape_eta_3;
            shape(16) = shape_xi_2 * shape_eta_3;

            naturalDerivatives = sym(zeros(2, nodes_length));
            naturalDerivatives(1, :) = diff(shape, xi);
            naturalDerivatives(2, :) = diff(shape, eta);

            shapeQ16 = matlabFunction(shape);
            naturalDerivativesQ16 = matlabFunction(naturalDerivatives);

            f = @shapeFunctionQ16;

    end

    function [shape, naturalDerivatives] = shapeFunctionQ16(xi, eta)

        shape = shapeQ16(xi, eta);

        naturalDerivatives = naturalDerivativesQ16(xi, eta);

    end

    function [shape, naturalDerivatives] = shapeFunctionQ4(xi, eta)

        shape = 1 / 4 * [ (1 - xi) * (1 - eta), (1 + xi) * (1 - eta), (1 + xi) * (1 + eta), (1 - xi) * (1 + eta)];

        naturalDerivatives = 1 / 4 * [
            - (1 - eta), 1 - eta, 1 + eta, - (1 + eta);
            - (1 - xi), - (1 + xi), 1 + xi, 1 - xi;
        ];

    end

    function [shape, naturalDerivatives] = shapeFunctionQ8(xi, eta)

        shape = 1 / 4 * [
            (1-xi)*(1-eta)*(-xi-eta-1), ...
            (1+xi)*(1-eta)*(xi-eta-1), ...
            (1+xi)*(1+eta)*(xi+eta-1), ...
            (1-xi)*(1+eta)*(-xi+eta-1), ...
            2*(1-eta)*(1-xi^2), ...
            2*(1+xi)*(1-eta^2), ...
            2*(1+eta)*(1-xi^2), ...
            2*(1-xi)*(1-eta^2)
        ];

        naturalDerivatives = [
            - ((eta - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            ((eta - 1)*(eta - xi + 1))/4 - ((eta - 1)*(xi + 1))/4, ...
            ((eta + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            ((eta + 1)*(xi - eta + 1))/4 + ((eta + 1)*(xi - 1))/4, ....
            (xi*(2*eta - 2))/2, ...
            1/2 - eta^2/2, ...
            -(xi*(2*eta + 2))/2, ...
            eta^2/2 - 1/2;

            - ((xi - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            ((xi + 1)*(eta - xi + 1))/4 + ((eta - 1)*(xi + 1))/4, ...
            ((xi + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            ((xi - 1)*(xi - eta + 1))/4 - ((eta + 1)*(xi - 1))/4, ...
            xi^2/2 - 1/2, ....
            -(eta*(2*xi + 2))/2, ...
            1/2 - xi^2/2, ...
            (eta*(2*xi - 2))/2
        ];

    end

    function [shape, naturalDerivatives] = shapeFunctionQ9(xi, eta)

        shape = [
            (eta*xi*(eta - 1)*(xi - 1))/4, ...
            (eta*xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            (eta*xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            (eta*xi*(eta + 1)*(xi - 1))/4, ...
            -(eta*(eta - 1)*(xi - 1)*(xi + 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1)*(eta + 1), ...
            -(eta*(eta + 1)*(xi - 1)*(xi + 1))/2, ...
            -(xi*(eta - 1)*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(eta + 1)*(xi - 1)*(xi + 1)
        ];

        naturalDerivatives = [
            (eta*xi*(eta - 1))/4 + (eta*(eta - 1)*(xi - 1))/4,...
            (eta*xi*(eta - 1))/4 + (eta*(xi/2 + 1/2)*(eta - 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(xi/2 + 1/2)*(eta + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(eta + 1)*(xi - 1))/4,...
            -(eta*(eta - 1)*(xi - 1))/2 - (eta*(eta - 1)*(xi + 1))/2,...
            -(xi/2 + 1/2)*(eta - 1)*(eta + 1) - (xi*(eta - 1)*(eta + 1))/2,...
            -(eta*(eta + 1)*(xi - 1))/2 - (eta*(eta + 1)*(xi + 1))/2,...
            -(xi*(eta - 1)*(eta + 1))/2 - ((eta - 1)*(eta + 1)*(xi - 1))/2,...
            (eta - 1)*(eta + 1)*(xi - 1) + (eta - 1)*(eta + 1)*(xi + 1);

            (eta*xi*(xi - 1))/4 + (xi*(eta - 1)*(xi - 1))/4, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            (eta*xi*(xi - 1))/4 + (xi*(eta + 1)*(xi - 1))/4, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta - 1)*(xi - 1)*(xi + 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1) - xi*(xi/2 + 1/2)*(eta + 1), ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta + 1)*(xi - 1)*(xi + 1))/2, ...
            -(xi*(eta - 1)*(xi - 1))/2 - (xi*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(xi - 1)*(xi + 1) + (eta + 1)*(xi - 1)*(xi + 1)
        ];

    end

    function [shape, naturalDerivatives] = shapeFunctionQ8AlongBoundary(xi, eta)

        shape = 1 / 4 * [
            (1-xi)*(1-eta)*(-xi-eta-1), ...
            2*(1-eta)*(1-xi^2), ...
            (1+xi)*(1-eta)*(xi-eta-1), ...
            2*(1+xi)*(1-eta^2), ...
            (1+xi)*(1+eta)*(xi+eta-1), ...
            2*(1+eta)*(1-xi^2), ...
            (1-xi)*(1+eta)*(-xi+eta-1), ...
            2*(1-xi)*(1-eta^2)
        ];

        naturalDerivatives = [
            - ((eta - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            (xi*(2*eta - 2))/2, ...
            ((eta - 1)*(eta - xi + 1))/4 - ((eta - 1)*(xi + 1))/4, ...
            1/2 - eta^2/2, ...
            ((eta + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            -(xi*(2*eta + 2))/2, ...
            ((eta + 1)*(xi - eta + 1))/4 + ((eta + 1)*(xi - 1))/4, ....
            eta^2/2 - 1/2;

            - ((xi - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
            xi^2/2 - 1/2, ....
            ((xi + 1)*(eta - xi + 1))/4 + ((eta - 1)*(xi + 1))/4, ...
            -(eta*(2*xi + 2))/2, ...
            ((xi + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
            1/2 - xi^2/2, ...
            ((xi - 1)*(xi - eta + 1))/4 - ((eta + 1)*(xi - 1))/4, ...
            (eta*(2*xi - 2))/2
        ];

    end

    function [shape, naturalDerivatives] = shapeFunctionQ9AlongBoundary(xi, eta)

        shape = [
            (eta*xi*(eta - 1)*(xi - 1))/4, ...
            -(eta*(eta - 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1)*(eta + 1), ...
            (eta*xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            -(eta*(eta + 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(eta + 1)*(xi - 1))/4, ...
            -(xi*(eta - 1)*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(eta + 1)*(xi - 1)*(xi + 1)
        ];

        naturalDerivatives = [
            (eta*xi*(eta - 1))/4 + (eta*(eta - 1)*(xi - 1))/4,...
            -(eta*(eta - 1)*(xi - 1))/2 - (eta*(eta - 1)*(xi + 1))/2,...
            (eta*xi*(eta - 1))/4 + (eta*(xi/2 + 1/2)*(eta - 1))/2,...
            -(xi/2 + 1/2)*(eta - 1)*(eta + 1) - (xi*(eta - 1)*(eta + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(xi/2 + 1/2)*(eta + 1))/2,...
            -(eta*(eta + 1)*(xi - 1))/2 - (eta*(eta + 1)*(xi + 1))/2,...
            (eta*xi*(eta + 1))/4 + (eta*(eta + 1)*(xi - 1))/4,...
            -(xi*(eta - 1)*(eta + 1))/2 - ((eta - 1)*(eta + 1)*(xi - 1))/2,...
            (eta - 1)*(eta + 1)*(xi - 1) + (eta - 1)*(eta + 1)*(xi + 1);

            (eta*xi*(xi - 1))/4 + (xi*(eta - 1)*(xi - 1))/4, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta - 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            -xi*(xi/2 + 1/2)*(eta - 1) - xi*(xi/2 + 1/2)*(eta + 1), ...
            (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            -(eta*(xi - 1)*(xi + 1))/2 - ((eta + 1)*(xi - 1)*(xi + 1))/2, ...
            (eta*xi*(xi - 1))/4 + (xi*(eta + 1)*(xi - 1))/4, ...
            -(xi*(eta - 1)*(xi - 1))/2 - (xi*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(xi - 1)*(xi + 1) + (eta + 1)*(xi - 1)*(xi + 1)
        ];

    end

end
