% .............................................................     
    function [shape,naturalDerivatives]=shapeFunctionQ9(xi,eta)

    % shape function and derivatives for Q9 elements
    % shape : Shape functions
    % naturalDerivatives: derivatives w.r.t. xi and eta 
    % xi, eta: natural coordinates (-1 ... +1)
   
    shape=[ (eta*xi*(eta - 1)*(xi - 1))/4, ...
            (eta*xi*(xi/2 + 1/2)*(eta - 1))/2, ...
            (eta*xi*(xi/2 + 1/2)*(eta + 1))/2, ...
            (eta*xi*(eta + 1)*(xi - 1))/4, ...
           -(eta*(eta - 1)*(xi - 1)*(xi + 1))/2, ...
           -xi*(xi/2 + 1/2)*(eta - 1)*(eta + 1), ...
           -(eta*(eta + 1)*(xi - 1)*(xi + 1))/2, ...
           -(xi*(eta - 1)*(eta + 1)*(xi - 1))/2, ...
            (eta - 1)*(eta + 1)*(xi - 1)*(xi + 1)];
    naturalDerivatives=...
[(eta*xi*(eta - 1))/4 + (eta*(eta - 1)*(xi - 1))/4,...
 (eta*xi*(eta - 1))/4 + (eta*(xi/2 + 1/2)*(eta - 1))/2,...
 (eta*xi*(eta + 1))/4 + (eta*(xi/2 + 1/2)*(eta + 1))/2,...
 (eta*xi*(eta + 1))/4 + (eta*(eta + 1)*(xi - 1))/4,...
-(eta*(eta - 1)*(xi - 1))/2 - (eta*(eta - 1)*(xi + 1))/2,...
-(xi/2 + 1/2)*(eta - 1)*(eta + 1) - (xi*(eta - 1)*(eta + 1))/2,...
-(eta*(eta + 1)*(xi - 1))/2 - (eta*(eta + 1)*(xi + 1))/2,...
-(xi*(eta - 1)*(eta + 1))/2 - ((eta - 1)*(eta + 1)*(xi - 1))/2,...
 (eta - 1)*(eta + 1)*(xi - 1) + (eta - 1)*(eta + 1)*(xi + 1);
 (eta*xi*(xi - 1))/4 + (xi*(eta - 1)*(xi - 1))/4, ...
 (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta - 1))/2, ...
 (eta*xi*(xi/2 + 1/2))/2 + (xi*(xi/2 + 1/2)*(eta + 1))/2, ...
 (eta*xi*(xi - 1))/4 + (xi*(eta + 1)*(xi - 1))/4, ...
-(eta*(xi - 1)*(xi + 1))/2 - ((eta - 1)*(xi - 1)*(xi + 1))/2, ...
-xi*(xi/2 + 1/2)*(eta - 1) - xi*(xi/2 + 1/2)*(eta + 1), ...
-(eta*(xi - 1)*(xi + 1))/2 - ((eta + 1)*(xi - 1)*(xi + 1))/2, ...
-(xi*(eta - 1)*(xi - 1))/2 - (xi*(eta + 1)*(xi - 1))/2, ...
 (eta - 1)*(xi - 1)*(xi + 1) + (eta + 1)*(xi - 1)*(xi + 1)];
          

    end % end function shapeFunctionQ9
  
