% .............................................................     
    function [shape,naturalDerivatives]=shapeFunctionQ9(xi,eta)

    % shape function and derivatives for Q6 elements
    % shape : Shape functions
    % naturalDerivatives: derivatives w.r.t. xi and eta 
    % xi, eta: natural coordinates (-1 ... +1)
    
    shape=zeros(1, 8);
    shape(5) = (1-xi^2)*(1-eta)/2;
    shape(6) = (1-eta^2)*(1+xi)/2;
    shape(7) = (1-xi^2)*(1+eta)/2;
    shape(8) = (1-eta^2)*(1-xi)/2;
    shape(1) = (1-xi)*(1-eta)/4 - (shape(5) + shape(8))/2;
    shape(2) = (1+xi)*(1-eta)/4 - (shape(5) + shape(6))/2;
    shape(3) = (1+xi)*(1+eta)/4 - (shape(6) + shape(7))/2;
    shape(4) = (1-xi)*(1+eta)/4 - (shape(7) + shape(8))/2;
    naturalDerivatives=...
[ -((eta + 2*xi)*(eta - 1))/4,...
((eta - 2*xi)*(eta - 1))/4,...
((eta + 2*xi)*(eta + 1))/4,...
-((eta - 2*xi)*(eta + 1))/4,...
xi*(eta - 1),...
1/2 - eta^2/2,...
-xi*(eta + 1),...
eta^2/2 - 1/2;
-((2*eta + xi)*(xi - 1))/4,...
((xi + 1)*(2*eta - xi))/4,...
((2*eta + xi)*(xi + 1))/4,...
-((xi - 1)*(2*eta - xi))/4,...
xi^2/2 - 1/2,...
-eta*(xi + 1),...
1/2 - xi^2/2,...
eta*(xi - 1)];
          

    end % end function shapeFunctionQ6
  
