function [shape, diff_shape] = shape_function_Q8(xi, eta)
%
% shape function and derivatives for Q8 elements.
%
% @since 1.0.0
% @param {sym} [xi] natural coordinates (-1  ... +1).
% @param {sym} [eta] natural coordinates (-1  ... +1).
% @param {array} [shape] Shape functions.
% @return {array} [diff_shape] derivatives w.r.t. xi and eta.

    shape = [
        (1-xi)*(1-eta)*(-xi-eta-1), ...
        2*(1-eta)*(1-xi^2), ...
        (1+xi)*(1-eta)*(xi-eta-1), ...
        2*(1+xi)*(1-eta^2), ...
        (1+xi)*(1+eta)*(xi+eta-1), ...
        2*(1+eta)*(1-xi^2), ...
        (1-xi)*(1+eta)*(-xi+eta-1), ...
        2*(1-xi)*(1-eta^2)
    ];

    diff_shape = [
        - ((eta - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
        (xi*(2*eta - 2))/2, ...
        ((eta - 1)*(eta - xi + 1))/4 - ((eta - 1)*(xi + 1))/4, ...
        1/2 - eta^2/2, ...
        ((eta + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
        -(xi*(2*eta + 2))/2, ...
        ((eta + 1)*(xi - eta + 1))/4 + ((eta + 1)*(xi - 1))/4, ....
        eta^2/2 - 1/2;
        - ((xi - 1)*(eta + xi + 1))/4 - ((eta - 1)*(xi - 1))/4, ...
        xi^2/2 - 1/2, ....
        ((xi + 1)*(eta - xi + 1))/4 + ((eta - 1)*(xi + 1))/4, ...
        -(eta*(2*xi + 2))/2, ...
        ((xi + 1)*(eta + xi - 1))/4 + ((eta + 1)*(xi + 1))/4, ...
        1/2 - xi^2/2, ...
        ((xi - 1)*(xi - eta + 1))/4 - ((eta + 1)*(xi - 1))/4, ...
        (eta*(2*xi - 2))/2
    ];

end
